version: "2"

linters:
  default: none
  enable:
    - logcheck
  settings:
    custom:
      logcheck:
        type: "module"
        description: Linter for log messages
        settings:
          sensitive-keywords: "password,key,secret,token,customSensitiveKeyword"
          watched-logs: |
            {
              "my-custom-logger": {
                "functions": {
                  "Info": 0,
                  "ErrorCtx": 1
                },
                "methods": {
                  "Logger": {
                    "Log": 0
                  }
                }
              }
            }